task: pl
mode: map
root_path: data/RadioMapSeer
prep_out_dir: outputs/dataset
model_ckpt: outputs/checkpoints/pl/global_pl_r400.pth
local_head_dir: outputs/checkpoints/pl/local_heads_pl_r400
outputs_dir: outputs/predictions/pl
save_visuals: true
save_strategies: true
export_extra: true
city_filter: ""
model_filter: ""
do_kpi: false
do_pl: true
trust_ckpt: true
alpha: 1.0
beta: 1.0
conf_nlos: 0.5
