task: kpi
scenario: Medium
users_dir: outputs/dataset/users
users_kpi_dir: outputs/dataset/users_kpi
dataset_prep_output_dir: outputs/dataset
save_dir: outputs/checkpoints/kpi
init_ckpt: ""
rounds: 400
local_epochs: 3
lr: 0.00026352989957644847
batch_size: 128
seed: 2025
personalized: true
loss: huber
huber_delta: 0.5678308362384664
head_lr_mult: 1.4257782865726316
two_layer_head: true
head_dropout: 0.25063511246027054
compress: sparse8
upload_ratio: 0.3709044684802143
quant_bits: 8
local_sync: 1
log_comm: true
eval_use_global_head: false
clip_grad: 1.8785657134034506
use_ema: false
ema_decay: 0.9844872387387853
kpi_lr_mult: 1.7651878818775586
kpi_head_dropout: 0.12075679951163695
amp: true
